### ISSUE TITLE
Disables scrolling

### ISSUE THREAD

**Issue by Merri** [Merri/react-tap-or-click#1]
Needs some more complexity so that scrolling will be allowed. Click should happen from `onTouchEnd` instead of `onTouchStart`. Don't know yet if X and Y should be tracked.

**Comment by nuschk** [comment]
It seems you've already solved that on on master, right? It would be great if you could update the npm package then!

BTW, thanks for that great (and simple) solution!

**Comment by Merri** [comment]
Yes, I did some changes, but I haven't had the time to properly test them. It probably works better than what is currently out now so I just pushed 0.0.2 out. Will be nice if you can give feedback on it!

**Comment by nuschk** [comment]
I think the changes are fine. There is one problem that prevents us from deploying it though. 

We would like to use tap clicks for navigation mostly. That means the event receiving component is often removed from the DOM after the click has been handled. However, with the current implementation, the IOS browser will still generate a click event 300ms later. I guess this is because the component receiving the touchStart event is long gone by then and there's no handler to block that click event.

So, wouldn't it be possible to prevent the click event globally? I really didn't invest too much into the problem, so this might be an obviously wrong way to do it, of course.

**Comment by Merri** [comment]
Humm, you probably have a true one page app... I don't have a site ready to test against that case as the site I primarily work on still works in the classic mode of always reloading the entire page. In the other hand I'm about to go on my Christmas travel so I have too limited time to debug anyway.

If you make a local copy and increase the timeout in touchEnd event, will the problem remain?

**Comment by nuschk** [comment]
Yes, it remains. I think it's because the ghost click event isn't actually triggered on the same element (that element is long gone), but on the element that is there after our route change. Thus, there's no way the click event is being bubbled to the same handler.

The way I see it, we have two options:

- Call event.preventDefault() each time you call the callback in touchEnd(). This prevents the ghost click generation in most browsers.
- Capture click events globally (on body, using capture=true) and stop them up to X ms (where X may be as small as 20ms) after a touchEnd event resulted in calling the callback.

You could possibly even combine the two. I have tried the first one, which seems to work on IOS Safari. On Android, there will still be a ghost click, but it ought to be faster when using a responsive web design (see link below). I don't think it would harm to implement both, without actually checking for the device.

This article helped me understand the issue better, you have probably seen it as well:
http://ariatemplates.com/blog/2014/05/ghost-clicks-in-mobile-browsers/

**Comment by Merri** [comment]
I spent a bit of time on this and added support for scrolling as well as busting clicks. Does it work for you now on all devices? I can't test on a real Android atm, I'm limited to:

1. iOS 9 Safari
2. iOS 9 Chrome
3. Desktop Chrome mobile view
4. Desktop Firefox responsive view with touch events
5. Regular desktop browsers

In all of those I don't get duplicate clicks and scrolling via touch does not trigger a click.

**Comment by nuschk** [comment]
Wow, thanks for the speedy work and the test pen. 

I don't know if the coordinates based clickbuster is really needed on today's devices (for responsive layouts at least). It sure should solve the problem, though.

On my (two) android devices, the fix works perfectly on Chrome and Firefox. Both devices are running on Lollipop. I will have to check for older devices using an emulator, but that has to wait a few days.

**Comment by Merri** [comment]
Great!

The click buster is a requirement as the clicks do happen after element has disappeared. I also decided to not use the iPhone preventDefault trick so it works with the same logic as Androids.

I guess the solution is now solid enough that I might even consider bumping the version to 1.0.0 - but I probably should wait for some more feedback just in case there are some other unexpected cases (double clicks?) and try to remember to do some testing once I'm back to my usual resources at work.

I open a new issue for testing and close this one :)
